# 1. 慢命令判定阈值，单位：微秒，生产级建议配置为10000微秒（10毫秒）
# 表示执行耗时超过10毫秒的命令，都会被记录到慢查询日志；
# 设为0表示记录所有命令的执行日志，设为负数表示关闭慢查询日志记录；
slowlog-log-slower-than 10000

# 2. 慢查询日志在内存中保存的最大条数，生产级建议配置为10000条
# 采用先进先出（FIFO）队列机制，超过最大条数时，最旧的慢查询记录会被自动淘汰；
# 设为0表示不限制条数，但会增加内存占用量，建议根据业务内存上限调整；
slowlog-max-len 10000